execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~ ~ ~ air 0 say Battle Settings ]:
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-1 ~ ~ stone 0 say Central Spawn: §oOff§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-1 ~ ~ dirt 0 say Central Spawn: §oOn§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-2 ~ ~ stone 0 say Round Length: §oShort§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-2 ~ ~ dirt 0 say Round Length: §oNormal§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-2 ~ ~ grass 0 say Round Length: §oLong§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-3 ~ ~ stone 0 say Map Voting: §oOff§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-3 ~ ~ dirt 0 say Map Voting: §oOn§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-4 ~ ~ stone 0 say Natural Regeneration: §oOff§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-4 ~ ~ air 0 say Natural Regeneration: §oOff§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-4 ~ ~ dirt 0 say Natural Regeneration: §oOn§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-5 ~ ~ stone 0 say Map Size: §oAuto§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-5 ~ ~ dirt 0 say Map Size: §oSmall§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-5 ~ ~ grass 0 say Map Size: §oLarge§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-5 ~ ~ cobblestone 0 say Map Size: §oLarge+§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-7 ~ ~ stone 0 say Spectator Mode: §oInvisible§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-7 ~ ~ dirt 0 say Spectator Mode: §oBat§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-7 ~ ~ grass 0 say Spectator Mode: §oParrot§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-7 ~ ~ cobblestone 0 say Spectator Mode: §oVex§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-7 ~ ~ planks 0 say Spectator Mode: §oHead§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-6 ~ ~ stone 0 say Hunger Settings: §oNormal§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-6 ~ ~ dirt 0 say Hunger Settings: §oNo Starving§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-6 ~ ~ grass 0 say Hunger Settings: §oNo Hunger§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-6 ~ ~ cobblestone 0 say Hunger Settings: §oAlways Hungry§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-8 ~ ~ stone 0 say Small Inventory: §oOff§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-8 ~ ~ dirt 0 say Small Inventory: §oOn§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-9 ~ ~ stone 0 say Game Size: §o8 players§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-9 ~ ~ dirt 0 say Game Size: §o16 players§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 0 say Lives per Round: §o1§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 1 say Lives per Round: §o2§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 2 say Lives per Round: §o3§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 3 say Lives per Round: §o4§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 4 say Lives per Round: §o5§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 5 say Lives per Round: §o6§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 6 say Lives per Round: §o7§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 7 say Lives per Round: §o8§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 8 say Lives per Round: §o9§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 9 say Lives per Round: §o10§r ]
execute @e[type=armor_stand,name=§] ~ ~ ~ detect ~-10 ~ ~ log 10 say Lives per Round: §oInfinite§r ]