name: BattleGamemode
version: '1.0'
main: me.dillionweaver.battlegamemode.BattleGamemode
api-version: '1.20'
authors: [Dillion Weaver]
description: A plugin that brings back the Battle Gamemode from the legacy console versions of Minecraft!
commands:
  BattleStartGame:
    description: Starts the game at a given X, Y, and Z coordinate, a map id, or a map name.
    usage: /<command>
  BattleEndGame:
    description: Ends the game and can only be used by an Admin.
    usage: /<command>
  BattleRegisterWorld:
    description: Adds a world to the server and registers it with the Battle gamemode.
    usage: /<command>
  BattleSendMeToWorld:
    description: Sends command sender to world.
    usage: /<command>