name: GlideGamemode
version: '1.0'
main: me.dillionweaver.elytragamemode.GlideGamemode
api-version: '1.20'
authors: [Dillion Weaver]
description: A plugin that brings back the Elytra Gamemode from the legacy console versions of Minecraft! 
commands:
  GlideStartGame:
    description: Starts the game at a given X, Y, and Z coordinate, a map id, or a map name.
    usage: /<command>
  GlideEndGame:
    description: Ends the game and can only be used by an Admin.
    usage: /<command>
  GlideRegisterWorld:
    description: Adds a world to the server and registers it with Glide.
    usage: /<command>
  GlideSendMeToWorld:
    description: Sends command sender to world.
    usage: /<command>